namespace Portfolio.Application.DTOs.Content;

public sealed record ProjectDto(
    Guid Id,
    string Title,
    string Slug,
    string? ShortDescription,
    string? FullDescription,
    string? Category,
    List<string> Technologies,
    string? Thumbnail,
    string? FeaturedImage,
    string? LiveUrl,
    string? GithubUrl,
    string? FigmaUrl,
    string? CaseStudyUrl,
    string? Year,
    string? Role,
    string? Client,
    string? Problem,
    string? Goal,
    string? Contribution,
    string? Process,
    List<string> Features,
    string? Challenges,
    string? Solution,
    string? Results,
    int DisplayOrder,
    bool IsFeatured,
    bool IsPublished,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    List<ProjectImageDto> Images);

public sealed record ProjectImageDto(Guid Id, string ImageUrl, string? AltText, int DisplayOrder);

public sealed record ProjectUpsertDto(
    string Title,
    string Slug,
    string? ShortDescription,
    string? FullDescription,
    string? Category,
    List<string>? Technologies,
    string? Thumbnail,
    string? FeaturedImage,
    string? LiveUrl,
    string? GithubUrl,
    string? FigmaUrl,
    string? CaseStudyUrl,
    string? Year,
    string? Role,
    string? Client,
    string? Problem,
    string? Goal,
    string? Contribution,
    string? Process,
    List<string>? Features,
    string? Challenges,
    string? Solution,
    string? Results,
    int DisplayOrder,
    bool IsFeatured,
    bool IsPublished,
    List<ProjectImageUpsertDto>? Images);

public sealed record ProjectImageUpsertDto(Guid? Id, string ImageUrl, string? AltText, int DisplayOrder);
